# Generated by Django 5.0.4 on 2024-04-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_alter_departamentos_funcionando'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('short_name', models.CharField(max_length=20, verbose_name='Nombre corto')),
                ('Funcionando', models.BooleanField(default=False, verbose_name='Funcionando  ')),
            ],
        ),
        migrations.DeleteModel(
            name='Departamentos',
        ),
    ]
