# Generated by Django 5.0.4 on 2024-04-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0004_departamento_delete_departamentos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='Funcionando',
            new_name='funcionando',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='Name',
            new_name='name',
        ),
    ]
