# Generated by Django 5.0.4 on 2024-04-09 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0005_rename_funcionando_departamento_funcionando_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Nombre  ')),
                ('las_name', models.CharField(max_length=11, verbose_name='Apelido  ')),
                ('Job', models.CharField(choices=[('0', 'Contador '), ('1', 'Gerente '), ('2', 'Economista '), ('3', 'Otro  ')], max_length=1, verbose_name='Labor ')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
            ],
        ),
    ]
