# Generated by Django 5.0.4 on 2024-04-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_alter_empleado_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Job',
            field=models.CharField(choices=[('0', 'Contador '), ('1', 'Gerente '), ('2', 'Economista '), ('3', 'Programador'), ('3', 'Otro')], max_length=1, verbose_name='Labor '),
        ),
    ]
