# Generated by Django 5.0.4 on 2024-04-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_alter_empleado_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='Habilidades',
            new_name='habilidades',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='Job',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='las_name',
            new_name='last_name',
        ),
    ]
