# Generated by Django 5.0.4 on 2024-04-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_rename_habilidades_empleado_habilidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'Contador '), ('1', 'Gerente '), ('2', 'Economista '), ('3', 'Programador'), ('4', 'Otro')], max_length=1, verbose_name='Labor '),
        ),
    ]
