# Generated by Django 5.0.6 on 2024-06-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0010_alter_empleado_hojavia'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nombres completos'),
        ),
    ]
